[project]
name = "boilerplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.4",
    "django-environ>=0.12.0",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
